import { User } from "@/types/user";

export const userMockup: User[] = [
  {
    id: 1,
    name: "Nadia Sukma",
    username: "nadia.sukma",
    email: "nadia.sukma@example.id",
    company: { name: "Nusantara Tech" },
  },
  {
    id: 2,
    name: "Nayla Siregar",
    username: "nayla.siregar",
    email: "nayla.siregar@example.id",
    company: { name: "Garuda Tech" },
  },
  {
    id: 3,
    name: "Mega Fadillah",
    username: "mega.fadillah",
    email: "mega.fadillah@example.id",
    company: { name: "Samudra Tech" },
  },
  {
    id: 4,
    name: "Hanifa Firmansyah",
    username: "hanifa.firmansyah",
    email: "hanifa.firmansyah@example.id",
    company: { name: "Sahabat Tech" },
  },
  {
    id: 5,
    name: "Ahmad Siregar",
    username: "ahmad.siregar",
    email: "ahmad.siregar@example.id",
    company: { name: "Sejahtera Tech" },
  },
  {
    id: 6,
    name: "Nisa Nuraini",
    username: "nisa.nuraini",
    email: "nisa.nuraini@example.id",
    company: { name: "Mandiri Tech" },
  },
  {
    id: 7,
    name: "Rangga Hidayat",
    username: "rangga.hidayat",
    email: "rangga.hidayat@example.id",
    company: { name: "Prima Tech" },
  },
  {
    id: 8,
    name: "Hari Pratama",
    username: "hari.pratama",
    email: "hari.pratama@example.id",
    company: { name: "Citra Tech" },
  },
  {
    id: 9,
    name: "Rani Utami",
    username: "rani.utami",
    email: "rani.utami@example.id",
    company: { name: "Berkah Tech" },
  },
  {
    id: 10,
    name: "Wahyu Hidayat",
    username: "wahyu.hidayat",
    email: "wahyu.hidayat@example.id",
    company: { name: "Pelita Tech" },
  },
  {
    id: 11,
    name: "Dinda Saputri",
    username: "dinda.saputri",
    email: "dinda.saputri@example.id",
    company: { name: "Mega Tech" },
  },
  {
    id: 12,
    name: "Hendra Gunawan",
    username: "hendra.gunawan",
    email: "hendra.gunawan@example.id",
    company: { name: "Lintas Tech" },
  },
  {
    id: 13,
    name: "Taufik Saputri",
    username: "taufik.saputri",
    email: "taufik.saputri@example.id",
    company: { name: "Bintang Tech" },
  },
  {
    id: 14,
    name: "Wahyu Wijaya",
    username: "wahyu.wijaya",
    email: "wahyu.wijaya@example.id",
    company: { name: "Sentosa Tech" },
  },
  {
    id: 15,
    name: "Rizka Nuraini",
    username: "rizka.nuraini",
    email: "rizka.nuraini@example.id",
    company: { name: "Mitra Tech" },
  },
  {
    id: 16,
    name: "Shinta Ramadhan",
    username: "shinta.ramadhan",
    email: "shinta.ramadhan@example.id",
    company: { name: "Karya Tech" },
  },
  {
    id: 17,
    name: "Wulan Kurniawan",
    username: "wulan.kurniawan",
    email: "wulan.kurniawan@example.id",
    company: { name: "Anugerah Tech" },
  },
  {
    id: 18,
    name: "Bella Putra",
    username: "bella.putra",
    email: "bella.putra@example.id",
    company: { name: "Sinar Tech" },
  },
  {
    id: 19,
    name: "Dewi Saragih",
    username: "dewi.saragih",
    email: "dewi.saragih@example.id",
    company: { name: "Dwiputra Tech" },
  },
  {
    id: 20,
    name: "Naufal Anindita",
    username: "naufal.anindita",
    email: "naufal.anindita@example.id",
    company: { name: "Tunas Tech" },
  },
  {
    id: 21,
    name: "Reza Maulana",
    username: "reza.maulana",
    email: "reza.maulana@example.id",
    company: { name: "Global Tech" },
  },
  {
    id: 22,
    name: "Ilham Setiawan",
    username: "ilham.setiawan",
    email: "ilham.setiawan@example.id",
    company: { name: "Solusi Utama" },
  },
  {
    id: 23,
    name: "Aditya Siregar",
    username: "aditya.siregar",
    email: "aditya.siregar@example.id",
    company: { name: "Teknologi Utama" },
  },
  {
    id: 24,
    name: "Nisrina Anindita",
    username: "nisrina.anindita",
    email: "nisrina.anindita@example.id",
    company: { name: "Data Utama" },
  },
  {
    id: 25,
    name: "Wahyu Ramadhan",
    username: "wahyu.ramadhan",
    email: "wahyu.ramadhan@example.id",
    company: { name: "Digital Utama" },
  },
  {
    id: 26,
    name: "Eka Pradana",
    username: "eka.pradana",
    email: "eka.pradana@example.id",
    company: { name: "Media Utama" },
  },
  {
    id: 27,
    name: "Nayla Saragih",
    username: "nayla.saragih",
    email: "nayla.saragih@example.id",
    company: { name: "Jaya Tech" },
  },
  {
    id: 28,
    name: "Hari Hidayat",
    username: "hari.hidayat",
    email: "hari.hidayat@example.id",
    company: { name: "Langit Tech" },
  },
  {
    id: 29,
    name: "Fajar Laksmi",
    username: "fajar.laksmi",
    email: "fajar.laksmi@example.id",
    company: { name: "Cakra Tech" },
  },
  {
    id: 30,
    name: "Dewi Ramadhan",
    username: "dewi.ramadhan",
    email: "dewi.ramadhan@example.id",
    company: { name: "Seruni Tech" },
  },
  {
    id: 31,
    name: "Siti Saputri",
    username: "siti.saputri",
    email: "siti.saputri@example.id",
    company: { name: "Nusantara Solusi" },
  },
  {
    id: 32,
    name: "Raka Laksmi",
    username: "raka.laksmi",
    email: "raka.laksmi@example.id",
    company: { name: "Garuda Solusi" },
  },
  {
    id: 33,
    name: "Nayla Setiawan",
    username: "nayla.setiawan",
    email: "nayla.setiawan@example.id",
    company: { name: "Samudra Solusi" },
  },
  {
    id: 34,
    name: "Aisyah Santoso",
    username: "aisyah.santoso",
    email: "aisyah.santoso@example.id",
    company: { name: "Sahabat Solusi" },
  },
  {
    id: 35,
    name: "Taufik Setiawan",
    username: "taufik.setiawan",
    email: "taufik.setiawan@example.id",
    company: { name: "Sejahtera Solusi" },
  },
  {
    id: 36,
    name: "Hari Maulana",
    username: "hari.maulana",
    email: "hari.maulana@example.id",
    company: { name: "Mandiri Solusi" },
  },
  {
    id: 37,
    name: "Naufal Mahendra",
    username: "naufal.mahendra",
    email: "naufal.mahendra@example.id",
    company: { name: "Prima Solusi" },
  },
  {
    id: 38,
    name: "Rizal Setiawan",
    username: "rizal.setiawan",
    email: "rizal.setiawan@example.id",
    company: { name: "Citra Solusi" },
  },
  {
    id: 39,
    name: "Farhan Setiawan",
    username: "farhan.setiawan",
    email: "farhan.setiawan@example.id",
    company: { name: "Berkah Solusi" },
  },
  {
    id: 40,
    name: "Ilham Gunawan",
    username: "ilham.gunawan",
    email: "ilham.gunawan@example.id",
    company: { name: "Pelita Solusi" },
  },
  {
    id: 41,
    name: "Nisa Nugroho",
    username: "nisa.nugroho",
    email: "nisa.nugroho@example.id",
    company: { name: "Mega Solusi" },
  },
  {
    id: 42,
    name: "Laila Firmansyah",
    username: "laila.firmansyah",
    email: "laila.firmansyah@example.id",
    company: { name: "Lintas Solusi" },
  },
  {
    id: 43,
    name: "Fauzan Laksmi",
    username: "fauzan.laksmi",
    email: "fauzan.laksmi@example.id",
    company: { name: "Bintang Solusi" },
  },
  {
    id: 44,
    name: "Bayu Pertiwi",
    username: "bayu.pertiwi",
    email: "bayu.pertiwi@example.id",
    company: { name: "Sentosa Solusi" },
  },
  {
    id: 45,
    name: "Kurniawan Kurniawan",
    username: "kurniawan.kurniawan",
    email: "kurniawan.kurniawan@example.id",
    company: { name: "Mitra Solusi" },
  },
  {
    id: 46,
    name: "Dimas Gunawan",
    username: "dimas.gunawan",
    email: "dimas.gunawan@example.id",
    company: { name: "Karya Solusi" },
  },
  {
    id: 47,
    name: "Hendra Handayani",
    username: "hendra.handayani",
    email: "hendra.handayani@example.id",
    company: { name: "Anugerah Solusi" },
  },
  {
    id: 48,
    name: "Rizwan Wijaya",
    username: "rizwan.wijaya",
    email: "rizwan.wijaya@example.id",
    company: { name: "Sinar Solusi" },
  },
  {
    id: 49,
    name: "Yoga Kusuma",
    username: "yoga.kusuma",
    email: "yoga.kusuma@example.id",
    company: { name: "Dwiputra Solusi" },
  },
  {
    id: 50,
    name: "Yusuf Saputra",
    username: "yusuf.saputra",
    email: "yusuf.saputra@example.id",
    company: { name: "Tunas Solusi" },
  },
  {
    id: 51,
    name: "Kevin Pradana",
    username: "kevin.pradana",
    email: "kevin.pradana@example.id",
    company: { name: "Global Solusi" },
  },
  {
    id: 52,
    name: "Muhammad Permana",
    username: "muhammad.permana",
    email: "muhammad.permana@example.id",
    company: { name: "Solusi Utama" },
  },
  {
    id: 53,
    name: "Tiara Laksmi",
    username: "tiara.laksmi",
    email: "tiara.laksmi@example.id",
    company: { name: "Teknologi Utama" },
  },
  {
    id: 54,
    name: "Arif Santoso",
    username: "arif.santoso",
    email: "arif.santoso@example.id",
    company: { name: "Data Utama" },
  },
  {
    id: 55,
    name: "Hafid Putra",
    username: "hafid.putra",
    email: "hafid.putra@example.id",
    company: { name: "Digital Utama" },
  },
  {
    id: 56,
    name: "Naufal Halim",
    username: "naufal.halim",
    email: "naufal.halim@example.id",
    company: { name: "Media Utama" },
  },
  {
    id: 57,
    name: "Kurniawan Sukma",
    username: "kurniawan.sukma",
    email: "kurniawan.sukma@example.id",
    company: { name: "Jaya Solusi" },
  },
  {
    id: 58,
    name: "Elsa Handayani",
    username: "elsa.handayani",
    email: "elsa.handayani@example.id",
    company: { name: "Langit Solusi" },
  },
  {
    id: 59,
    name: "Siti Nugroho",
    username: "siti.nugroho",
    email: "siti.nugroho@example.id",
    company: { name: "Cakra Solusi" },
  },
  {
    id: 60,
    name: "Dewi Permana",
    username: "dewi.permana",
    email: "dewi.permana@example.id",
    company: { name: "Seruni Solusi" },
  },
  {
    id: 61,
    name: "Fajar Putra",
    username: "fajar.putra",
    email: "fajar.putra@example.id",
    company: { name: "Nusantara Digital" },
  },
  {
    id: 62,
    name: "Irfan Laksmi",
    username: "irfan.laksmi",
    email: "irfan.laksmi@example.id",
    company: { name: "Garuda Digital" },
  },
  {
    id: 63,
    name: "Nadia Kurniawan",
    username: "nadia.kurniawan",
    email: "nadia.kurniawan@example.id",
    company: { name: "Samudra Digital" },
  },
  {
    id: 64,
    name: "Agus Pangestu",
    username: "agus.pangestu",
    email: "agus.pangestu@example.id",
    company: { name: "Sahabat Digital" },
  },
  {
    id: 65,
    name: "Dinda Putra",
    username: "dinda.putra",
    email: "dinda.putra@example.id",
    company: { name: "Sejahtera Digital" },
  },
  {
    id: 66,
    name: "Yuni Kurniawan",
    username: "yuni.kurniawan",
    email: "yuni.kurniawan@example.id",
    company: { name: "Mandiri Digital" },
  },
  {
    id: 67,
    name: "Mega Pertiwi",
    username: "mega.pertiwi",
    email: "mega.pertiwi@example.id",
    company: { name: "Prima Digital" },
  },
  {
    id: 68,
    name: "Wahyu Handayani",
    username: "wahyu.handayani",
    email: "wahyu.handayani@example.id",
    company: { name: "Citra Digital" },
  },
  {
    id: 69,
    name: "Nisrina Saputri",
    username: "nisrina.saputri",
    email: "nisrina.saputri@example.id",
    company: { name: "Berkah Digital" },
  },
  {
    id: 70,
    name: "Yusuf Mahendra",
    username: "yusuf.mahendra",
    email: "yusuf.mahendra@example.id",
    company: { name: "Pelita Digital" },
  },
  {
    id: 71,
    name: "Yoga Nugroho",
    username: "yoga.nugroho",
    email: "yoga.nugroho@example.id",
    company: { name: "Mega Digital" },
  },
  {
    id: 72,
    name: "Budi Syahputra",
    username: "budi.syahputra",
    email: "budi.syahputra@example.id",
    company: { name: "Lintas Digital" },
  },
  {
    id: 73,
    name: "Nadya Prasetyo",
    username: "nadya.prasetyo",
    email: "nadya.prasetyo@example.id",
    company: { name: "Bintang Digital" },
  },
  {
    id: 74,
    name: "Farah Laksmi",
    username: "farah.laksmi",
    email: "farah.laksmi@example.id",
    company: { name: "Sentosa Digital" },
  },
  {
    id: 75,
    name: "Shinta Nuraini",
    username: "shinta.nuraini",
    email: "shinta.nuraini@example.id",
    company: { name: "Mitra Digital" },
  },
  {
    id: 76,
    name: "Nisa Wijaya",
    username: "nisa.wijaya",
    email: "nisa.wijaya@example.id",
    company: { name: "Karya Digital" },
  },
  {
    id: 77,
    name: "Zahra Saputra",
    username: "zahra.saputra",
    email: "zahra.saputra@example.id",
    company: { name: "Anugerah Digital" },
  },
  {
    id: 78,
    name: "Rizwan Maulana",
    username: "rizwan.maulana",
    email: "rizwan.maulana@example.id",
    company: { name: "Sinar Digital" },
  },
  {
    id: 79,
    name: "Rina Utami",
    username: "rina.utami",
    email: "rina.utami@example.id",
    company: { name: "Dwiputra Digital" },
  },
  {
    id: 80,
    name: "Fauzan Mahardika",
    username: "fauzan.mahardika",
    email: "fauzan.mahardika@example.id",
    company: { name: "Tunas Digital" },
  },
  {
    id: 81,
    name: "Yoga Mahendra",
    username: "yoga.mahendra",
    email: "yoga.mahendra@example.id",
    company: { name: "Global Digital" },
  },
  {
    id: 82,
    name: "Aqilah Nuraini",
    username: "aqilah.nuraini",
    email: "aqilah.nuraini@example.id",
    company: { name: "Solusi Utama" },
  },
  {
    id: 83,
    name: "Shinta Wibowo",
    username: "shinta.wibowo",
    email: "shinta.wibowo@example.id",
    company: { name: "Teknologi Utama" },
  },
  {
    id: 84,
    name: "Hafid Anindita",
    username: "hafid.anindita",
    email: "hafid.anindita@example.id",
    company: { name: "Data Utama" },
  },
  {
    id: 85,
    name: "Intan Nugroho",
    username: "intan.nugroho",
    email: "intan.nugroho@example.id",
    company: { name: "Digital Utama" },
  },
  {
    id: 86,
    name: "Hanifa Kusuma",
    username: "hanifa.kusuma",
    email: "hanifa.kusuma@example.id",
    company: { name: "Media Utama" },
  },
  {
    id: 87,
    name: "Rafi Permana",
    username: "rafi.permana",
    email: "rafi.permana@example.id",
    company: { name: "Jaya Digital" },
  },
  {
    id: 88,
    name: "Dewi Saputra",
    username: "dewi.saputra",
    email: "dewi.saputra@example.id",
    company: { name: "Langit Digital" },
  },
  {
    id: 89,
    name: "Aqilah Pratama",
    username: "aqilah.pratama",
    email: "aqilah.pratama@example.id",
    company: { name: "Cakra Digital" },
  },
  {
    id: 90,
    name: "Fikri Pertiwi",
    username: "fikri.pertiwi",
    email: "fikri.pertiwi@example.id",
    company: { name: "Seruni Digital" },
  },
  {
    id: 91,
    name: "Hafid Pradipta",
    username: "hafid.pradipta",
    email: "hafid.pradipta@example.id",
    company: { name: "Nusantara Data" },
  },
  {
    id: 92,
    name: "Nabila Suryani",
    username: "nabila.suryani",
    email: "nabila.suryani@example.id",
    company: { name: "Garuda Data" },
  },
  {
    id: 93,
    name: "Farhan Pratama",
    username: "farhan.pratama",
    email: "farhan.pratama@example.id",
    company: { name: "Samudra Data" },
  },
  {
    id: 94,
    name: "Dimas Pertiwi",
    username: "dimas.pertiwi",
    email: "dimas.pertiwi@example.id",
    company: { name: "Sahabat Data" },
  },
  {
    id: 95,
    name: "Rizka Saragih",
    username: "rizka.saragih",
    email: "rizka.saragih@example.id",
    company: { name: "Sejahtera Data" },
  },
  {
    id: 96,
    name: "Mega Mahendra",
    username: "mega.mahendra",
    email: "mega.mahendra@example.id",
    company: { name: "Mandiri Data" },
  },
  {
    id: 97,
    name: "Naufal Pertiwi",
    username: "naufal.pertiwi",
    email: "naufal.pertiwi@example.id",
    company: { name: "Prima Data" },
  },
  {
    id: 98,
    name: "Fadel Hidayat",
    username: "fadel.hidayat",
    email: "fadel.hidayat@example.id",
    company: { name: "Citra Data" },
  },
  {
    id: 99,
    name: "Putri Nuraini",
    username: "putri.nuraini",
    email: "putri.nuraini@example.id",
    company: { name: "Berkah Data" },
  },
  {
    id: 100,
    name: "Andi Kurniawan",
    username: "andi.kurniawan",
    email: "andi.kurniawan@example.id",
    company: { name: "Pelita Data" },
  },
];
